---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: Install prereq packages
  package: "{{ duo_authproxy_packages }}"

- name: Check if Duo Authentication Proxy is already installed
  stat:
    path: "{{ duo_authproxy_config_file }}"
  register: duo_authproxy_install

- name: Install Duo Authentication Proxy
  when: "not ansible_check_mode and (not duo_authproxy_install.stat.exists or duo_authproxy_reinstall)"
  shell: |
    cd {{ duo_authproxy_build_dir }};
    rm -f duoauthproxy-*-src.tgz
    wget --content-disposition {{ duo_authproxy_download_url }};
    tar xzf duoauthproxy-*-src.tgz;
    cd duoauthproxy-*-src;
    make;
    rm -rf /opt/duoauthproxy;
    ./duoauthproxy-build/install --install-dir /opt/duoauthproxy --service-user {{ duo_authproxy_service_user }} --log-group {{ duo_authproxy_log_group }} --create-init-script {{ duo_authproxy_init_script }}

- name: Configure Duo Authentication Proxy
  template:
    src: authproxy.cfg.j2
    dest: "{{ duo_authproxy_config_file }}"
    mode: '0600'
  notify: restart duoauthproxy
